### ISSUE TITLE
Incompatible with Seq 2020.5/Seq on Docker/Linux

### ISSUE THREAD

**Issue by nblumhardt** [mkaltner/Seq.App.Azure#1]
Hi! We've been testing Seq apps for compatibility with the next Seq version (2020.5), which will [host all apps using .NET 5](https://github.com/datalust/seq-tickets/issues/1066).

_Seq.App.Azure.EventHubs_ uses an old version of _WindowsAzure.ServiceBus_ that appears to pull in WCF as a dependency, and this won't work under the new runtime. If the project is no longer in use, that might not be a worry.

If you're still actively developing this project, and would like a hand to migrate forwards, we'd be happy to help, just let us know if that's the case.

Alternatively, if the project is "done" but others need to continue using it, we have internal tools we can use to re-package it in a way that will still load .NET Framework (compatible with Seq on Windows only), and would be glad to give this a shot if anyone needs it.

**Comment by andreminelli** [comment]
@HakanL and @mkaltner , is there any chance you can take a look on this?
@nblumhardt was interested in helping, and I can try, too.

**Comment by HakanL** [comment]
@andreminelli Completely forgot about this project. Unfortunately I'm not on the project where this was needed so I don't have a good way to test it. But I have upgraded it to .NET 5 and the Azure EventHubs dependency and pushed that code into master. However if you're in a position to test this then it would be very helpful. If it works then I can build and publish an updated Nuget package. Feel free to either comment on changes that I need to do, or submit PR.

**Comment by andreminelli** [comment]
Awesome! Thanks @HakanL .
I had never tested a Seq App before, but it seems pretty straighforward. 
I will try it until the end of this week, hopefully

**Comment by HakanL** [comment]
Nice, I know Michael did the implementation and testing of this when we built it (for a project we both worked on). I know he's not on a project currently where this is used, but if you can test that would be great!

**Comment by nblumhardt** [comment]
Great! If you need any help/pointers along the way @andreminelli, loop me in anytime :-)

**Comment by tuliorezende** [comment]
@HakanL I'm helping @andreminelli on some tests with the master content and I found some things
- Based on Seq Documentation about create [Seq Apps](https://docs.datalust.co/docs/writing-seq-apps) we need to insert the libraries on the package and after the changes, the generated package just contains the dll itself
- On my tests, I saw that I can just send the "Data.Properties" content. I was thinking to create some optional values, like Rendered Message and Template, and insert the EventType by default. Is there a way to use these properties outside the "Data.Properties" structure?

I'm editing the project changes in a fork to help too :) Later I'll submit in a pull request.

**Comment by HakanL** [comment]
@tuliorezende To be honest Michael did most of the work on this, but he was on my team and we designed the overall architecture (that included SEQ, Event Hubs and this Seq App) together. So I don't have a lot of details to share about what content/properties is sent. We used this in production at the time (6 years ago), but it is no longer in use (and we are no longer with that company). Michael is a friend though and we still work together so if needed I can ask him, but my guess is that he may not remember much more than I do about this Seq app. If you can submit a PR the I'm more than happy to accept that though and build the Nuget package.

**Comment by tuliorezende** [comment]
> @tuliorezende To be honest Michael did most of the work on this, but he was on my team and we designed the overall architecture (that included SEQ, Event Hubs and this Seq App) together. So I don't have a lot of details to share about what content/properties is sent. We used this in production at the time (6 years ago), but it is no longer in use (and we are no longer with that company). Michael is a friend though and we still work together so if needed I can ask him, but my guess is that he may not remember much more than I do about this Seq app. If you can submit a PR the I'm more than happy to accept that though and build the Nuget package.

Sure!

I've created #2 to allow you check the changes and nuget generation. Feel free to comment if you want some changes too.

**Comment by HakanL** [comment]
Perfect, I appreciate the contribution! I have just uploaded a new Nuget package, once published (a few minutes) please verify that it's all working and then we can close this ticket (1.5 years later ;) )
