### ISSUE TITLE
An item with the same key has already been added. Key: EventType

### ISSUE THREAD

**Issue by arthursoas** [mkaltner/Seq.App.Azure#3]
We are facing an error in adding our messages to the event hub, like the one below:

```
An error occurred while processing event data. An item with the same key has already been added. Key: EventType

System.ArgumentException: An item with the same key has already been added. Key: EventType
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Seq.App.Azure.EventHub.AzureEventHubReactor.On(Event`1 evt)
```

Followed right after by this error:

```
The event event-20d66fe6d95a08db1807adee08000000 could not be sent to {{instance-name}}.

System.ArgumentException: An item with the same key has already been added. Key: EventType
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Seq.App.Azure.EventHub.AzureEventHubReactor.On(Event`1 evt)
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 132
```

We do not remember changing any parameter on the app instance, and it's been happening for 3 months. Almost any log from our application generates a log for the failed integration.
This makes sense because the `EventType` aggregates similar events, so there will be multiple events with the same `EventType`.

Any ideas of what could be happening, or if there are some settings on the app instance we could set to solve this issue?

Thank you!

**Comment by HakanL** [comment]
Hi! Thanks for reporting this. I haven't been active on this project for quite some time, but if you can figure out a fix and submit a PR then I can build and push a new package.

**Comment by HakanL** [comment]
Hi @arthursoas I've just built a new package of this based on @nblumhardt PR. Neither of us have an environment currently where we can test this, so please take version 1.1.2 and test in your environment and report back.

**Comment by arthursoas** [comment]
Hi @HakanL and @nblumhardt, thank you for the fast response.
We tested the update here and it's working great!

You rock
